Repository finsweet/developer-starter, pull requests merged in 2022-10, with the labels that each got.

#18 Add(chore): jquery on dev mode only
  package.json
  pnpm-lock.yaml
Labels: enhancement

#19 add `--recursive` flag to the `update` script + update dependencies
  package.json
  pnpm-lock.yaml
Labels: dependencies

#20 Playwright and dependencies
  package.json
  playwright.config.ts
  pnpm-lock.yaml
Labels: enhancement, dependencies
